#  Numpy (Arrays)

* __single dimensional array is also called vector__
* __two dimensional array is also called matrix__
* __ndarray class can be used for both dimensions__
* __In tensor we use 3d arrays__

In [1]:
# this is from day-6
import numpy as np

a = np.array([1, 2, 3, 4])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [7]:
b = np.array([[1, 3, 4, 5,],
             [2, 3, 4, 5],
             [3, 4, 5, 6]])
b

array([[1, 3, 4, 5],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [8]:
type(b)

numpy.ndarray

In [16]:
c = np.ones(3)
c

array([1., 1., 1.])

In [21]:
d = np.zeros(4)
d

array([0., 0., 0., 0.])

In [29]:
e = np.arange(0, 11)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
e = np.arange(0, 11, 3)
e

array([0, 3, 6, 9])

In [49]:
e = np.linspace(2.0, 3.0, num=5, retstep=True)
e

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

## 2d arrays (rows, column) or you can say rows by columns eg:

In [51]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
type(a)

numpy.ndarray

In [59]:
b = np.array([[[1, 3, 4, 5],
             [2, 3, 4, 5],
             [3, 4, 5, 6]],
             
             [[4, 5, 6, 7],
             [5, 6, 7, 8],
             [6, 7, 8, 9]]])
type(b)

numpy.ndarray

In [63]:
np.linspace(1, 10, num=5, retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [69]:
np.arange(1, 11, 2.25)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [103]:
# we can concatenate different dimensional arrays vertically using vstack method:

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9 ,10]])
b = np.array([11, 12, 13, 14, 15])

c = np.vstack((a, b))
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [104]:
c.ndim

2

In [105]:
c.size

15

In [106]:
c.shape

(3, 5)

In [108]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [109]:
y = x[np.newaxis, :]
y

array([[0, 1, 2, 3, 4, 5]])

In [110]:
y.ndim

2